### ISSUE TITLE
Sentry Issues

### ISSUE THREAD

**Issue by Danton1983** [jrbudda/Sentry#101] opened 2013-03-29 11:31 UTC
Using newest dev build,

1) I can get a sentry down to 6 health and then after several large hits it will drop to 1 but not die by melee attacks.

2) If I use a bow it doesnt register that I am hitting it, It will kill the sentry and not respawn. 

3) Sometimes the sentry will be 10 blocks away and hitting me, I would reloag to have the same issue. I would have to remove the NPC and recreate it to resolve the issue

4) The sentry doesn't always attack correctly when holding certain items, it would chase me with a book instead of actually using the Bolt attack and sometimes it would use the bolt attack.

**Comment by mcmonkey4eva** [comment] 2013-05-23 03:01
None of these occur for me. Is this still a valid bug?

**Comment by michalet** [comment] 2013-07-26 10:20
I can confirm that the first bug is still valid. Using latest citizens dev build (914),  1.4.1 sentry and spigot 1041.

Sentries were working fine, then citizens were not working at all until both spigot and sentry+citizens were updated. But after the update, all sentries are immortal. No changes in settings since 1.5.

**Comment by jrbudda** [comment] 2013-07-29 06:03
Should be fixed. was API change in Denizen .9

**Closed as completed by jrbudda** 2013-07-29 06:03 UTC
