### ISSUE TITLE
Sentry death problems

### ISSUE THREAD

**Issue by TapaniV** [jrbudda/Sentry#119] opened 2013-05-16 18:24 UTC
I have discovered two issues relating to deaths of my sentries:
1. Sentry will drop the item it was carrying even with drops disabled, but the item is a "non-existing" item that can't be picked up. The item was given with the /sentry equip command.
2. The DIE command causes a nullpointerexecption when called from a death trigger:
   java.lang.NullPointerException
   at net.aufdemrand.denizen.scripts.commands.CommandExecuter.execute(CommandExecuter.java:54)
   at net.aufdemrand.denizen.scripts.ScriptEngine.revolve(ScriptEngine.java:43)
   at net.aufdemrand.denizen.scripts.ScriptQueue.revolve(ScriptQueue.java:259)
   at net.aufdemrand.denizen.scripts.ScriptQueue.access$000(ScriptQueue.java:15)
   at net.aufdemrand.denizen.scripts.ScriptQueue$1.run(ScriptQueue.java:222)
   at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
   at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
   at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
   at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
   at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
   at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
   at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

Running latest builds of Citizens and Denizen with Sentry 1.3.5. DieLikePlayers setting is false if that matters

**Comment by jrbudda** [comment] 2013-05-21 19:58
Cant reproduce problem #1. with drops off my sentries don't drop anything. if you log out and back in and the item is gone, this is a client-side bug.

#2 will be fixed in next version.

**Closed as completed by jrbudda** 2013-05-21 19:58 UTC
